# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './templates/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(240, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setEnabled(True)
        self.label_17.setGeometry(QtCore.QRect(250, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(100, 270, 511, 141))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(540, 640, 75, 31))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(100, 480, 511, 141))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_key_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key_1.setGeometry(QtCore.QRect(100, 80, 511, 31))
        self.txt_key_1.setObjectName("txt_key_1")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_16.setObjectName("label_16")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(100, 640, 75, 31))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 480, 61, 16))
        self.label_19.setObjectName("label_19")
        self.btn_create_matrix = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create_matrix.setGeometry(QtCore.QRect(100, 120, 91, 31))
        self.btn_create_matrix.setObjectName("btn_create_matrix")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 430, 47, 13))
        self.label_21.setObjectName("label_21")
        self.txt_key_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key_2.setGeometry(QtCore.QRect(100, 430, 511, 31))
        self.txt_key_2.setObjectName("txt_key_2")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_22.setObjectName("label_22")
        self.txt_matrix = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_matrix.setGeometry(QtCore.QRect(100, 160, 511, 91))
        self.txt_matrix.setObjectName("txt_matrix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "Nguyễn Hữu Tài - 2280602800"))
        self.label_17.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label_18.setText(_translate("MainWindow", "Plaintext:"))
        self.label_16.setText(_translate("MainWindow", "Key:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encypt"))
        self.label_19.setText(_translate("MainWindow", "CipherText:"))
        self.btn_create_matrix.setText(_translate("MainWindow", "Create Matrix"))
        self.label_21.setText(_translate("MainWindow", "Key:"))
        self.label_22.setText(_translate("MainWindow", "Matrix:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
